### ISSUE TITLE
Feature: Cleanup chats (mass and single chat)

### ISSUE THREAD

**Issue by peperunas** [AugustDev/enchanted#10]
First of all, great job!

It would be great to be able to delete the chats. Single and entire days / all chats.

**Comment by AugustDev** [comment]
Great points @peperunas. Enchanted already has a feature to delete single chat by pressing and holding on the conversation

![simulator_screenshot_E2D065F9-A5AE-4094-B1C2-5F24CE76963B](https://github.com/AugustDev/enchanted/assets/5672094/fa50c4eb-6678-40ec-928d-7927e13c8d7a)

In addition I have added ability to delete daily conversations and all conversations in the settings

<img width="392" alt="image" src="https://github.com/AugustDev/enchanted/assets/5672094/c999dcf6-3564-47ec-8083-3c73ac01dcbd">

<img width="388" alt="image" src="https://github.com/AugustDev/enchanted/assets/5672094/24fea88c-ba84-4fe6-937a-f24b86d44d77">
