### ISSUE TITLE
Copy entire chat history

### ISSUE THREAD

**Issue by abhayap** [AugustDev/enchanted#106]
Hi, is there a way to copy the entire chat history to paste it somewhere else? I can only seem to copy individual questions or answers.

**Comment by AugustDev** [comment]
I was thinking about it, will add!

**Comment by AugustDev** [comment]
Implemented, will release new version of the app today!

<img width="1089" alt="image" src="https://github.com/AugustDev/enchanted/assets/5672094/ed11bbb1-bb2e-4786-b713-a2e67e1a012b">

**Comment by abhayap** [comment]
Thanks! It works great.
