### ISSUE TITLE
Feature: token count / context management

### ISSUE THREAD

**Issue by peperunas** [AugustDev/enchanted#11]
It would be great to know if the message about to be sent is going to fix in the conversation context.

In this way, we can avoid having garbled / nonsense back from the model.

**Comment by AugustDev** [comment]
Hi @peperunas, unfortunately Ollama currently does not expose model context length in the API. I have submitted an [issue](https://github.com/ollama/ollama/issues/2732) to address this and planning to support it as soon as it's implemented. For now will close the issue.
