### ISSUE TITLE
Bug: with long prompts, text disappears behind the UI elements of the textfield

### ISSUE THREAD

**Issue by ericwaetke** [AugustDev/enchanted#123]
When entering a prompt, text isn’t wrapping properly.
<img width="399" alt="Screenshot 2024-05-31 at 11 51 17" src="https://github.com/AugustDev/enchanted/assets/8260492/3f3a7f3e-381b-4b0c-b09b-6c7e45a31077">
<img width="222" alt="Screenshot 2024-05-31 at 11 51 30" src="https://github.com/AugustDev/enchanted/assets/8260492/9b498bd4-96c7-4d44-846d-10a756ea6d67">
There are just not wrapping at all in small window sizes

Here, the text is hidden behind the UI elements
<img width="779" alt="Screenshot 2024-05-31 at 11 52 43" src="https://github.com/AugustDev/enchanted/assets/8260492/4fcf9655-b5f4-4e3a-985d-e939b5850a37">

**Comment by tobiasleissner** [comment]
Already fixed, see here:
https://github.com/AugustDev/enchanted/pull/114

However, not merged yet.

**Comment by AugustDev** [comment]
Thanks for reporting, will be fixed in new release!
