### ISSUE TITLE
NEW FEATURE - Chat Sync

### ISSUE THREAD

**Issue by XenoUniv3rse** [AugustDev/enchanted#124]
Thanks for the great app. 

I would like to request chat sync between devices and maybe even a webapp so I can access it from any device.

**Comment by nurb2kea** [comment]
This web interface here works like a charme on any OS across the network ...
https://www.youtube.com/watch?v=8AOAARhf1ds

**Comment by XenoUniv3rse** [comment]
Yes I have Open WebUI setup and been using it for months. I am also looking for a mobile app. If Open WebUI can impalement the same/similar mobile app as enchanted it would be amazing.
