### ISSUE TITLE
Cannot refresh models list

### ISSUE THREAD

**Issue by hyjwei** [AugustDev/enchanted#15]
First of all, this is a very impressive and useful App! Thanks!

After I set ollama server address, it does load all available models and by default use the first model as the default one. One minor issue is that everytime the iOS reload this App or I start a new conversation, it forgets the last loaded model and always loads the first one, as #5 mentions.

The main issue for me is that it doesn't refresh models list after the initial one. If I delete model(s) from ollama server, these models still show up in the drop-down list. I don't know how to get it refreshed, re-saving server URI or swipe-up to close the app doesn't help.

If I select the removed model from the list, the App gives error: (in red color) The data couldn't be read because it is missing.

## Expected Behavior

There are a few options:
1. Force reloading models list when user over-swipe-down models list;
2. Force reloading models list when user starts a new conversation;
3. Force reloading models list automatically when the App starts; or
4. Add an option in Settings to allow user to reload models list from ollama server;

**Comment by AugustDev** [comment]
Hi @hyjwei thanks for the feedback! The models list should be refreshed after restart, if the problem still persists after latest version let me know and I will investigate deeper.

For now I added few points that you have mentioned

1. Models reloaded when user starts new conversation.
2. Default model can be specified in Settings.

<img width="386" alt="image" src="https://github.com/AugustDev/enchanted/assets/5672094/e779c8e7-6e99-4c18-bcf0-53a157ce5147">

I'm releasing new version of the app and as soon as it's approved by Apple these fixes will be live! I hope they will approve by the end of day!
