### ISSUE TITLE
Fix: MacOS app icon is larger than average

### ISSUE THREAD

**Issue by lukaemon** [AugustDev/enchanted#22]
Would be nice if they are all at the same scale. Thx for the open source app. 

<img width="78" alt="image" src="https://github.com/AugustDev/enchanted/assets/1643232/5ab5a0b8-c9f5-4c5a-af71-3b5210f2312e">

**Comment by AugustDev** [comment]
Well spotted, will fix!

**Comment by AugustDev** [comment]
Hi @lukaemon I fixed the issue 
<img width="183" alt="image" src="https://github.com/AugustDev/enchanted/assets/5672094/e2df1354-069d-4f1d-9cd4-da74ab556277">

I'm making new release now and it should be available on App Store later today or tomorrow!
