### ISSUE TITLE
Feature suggestion: sidebar and model list

### ISSUE THREAD

**Issue by lukaemon** [AugustDev/enchanted#26]
<img width="788" alt="Screenshot 2024-02-19 at 1 26 18 PM" src="https://github.com/AugustDev/enchanted/assets/1643232/3020a7bb-3f0e-4aa1-86fe-da6e23b5d88a">

1. Would be great that app remembers user's last sidebar status: hide or show. 
2. The list of available models is stale. May want to refresh the list per chat session or app restart?

Thanks for open source.

**Comment by AugustDev** [comment]
Thanks for reporting these issues. Will address!

**Comment by AugustDev** [comment]
Hi @lukaemon Currently the models are fetched

- When user starts the app
- When user clicks new conversation button
- When user changes settings

I'm also thinking to add periodic sync in the background, but later on.

Regarding memorising the sidebar, I will keep it in mind and adjust sometime within next 2 weeks.
