### ISSUE TITLE
Bug : Words / letters skipped

### ISSUE THREAD

**Issue by icelaglace** [AugustDev/enchanted#33]
Hello,

Enchanted 1.5.2 introduced an issue that wasn’t here before. 

If I now type a prompt on Enchanted, there’s a big change the text will be missing words or letters. 

If I type the same prompt on Ollama cmd, the prompt result is consistent. 

Model used : openchat:7b-v3.5-0106-q6_K
It also happens on every model I’ve tried like Mistral. 

![IMG_4008](https://github.com/AugustDev/enchanted/assets/18472117/e187d734-d601-4325-b915-bcd23e610e88)

![IMG_4009](https://github.com/AugustDev/enchanted/assets/18472117/fdf4b909-2dc2-4d5c-ae7e-2c24f621e13b)

It might have to do with the new JSON changes done for Ngrok?

I’m running ollama locally, Enchanted on iOS and iPadOS gives the same result on the same Wi-Fi, locally. 

Anything I can send to help with this ? 

Thank you for your work, it’s fantastic to use :)

**Comment by AugustDev** [comment]
Hi @icelaglace thanks for the issue, unfortunately I was not able to reproduce the issue.

![simulator_screenshot_B89FC41E-9FF5-4739-8202-6B6109EAAB41](https://github.com/AugustDev/enchanted/assets/5672094/72b75de8-cde9-4297-a8c0-d8b6b5d36c95)

Could you share exact steps to reproduce it?

**Comment by icelaglace** [comment]
Hello, and thanks for the help!
Sadly I’m not sure what is different on my end then. 

https://streamable.com/i83ch2

This is a video of me running Enchanted on one of my devices, you can see the words skipping on all models.

To be sure it’s not my Ollama instance, I tried with other clients and it does not happen on Open WebUI and Maid (Android Client).

I am not sure what I could do to see what’s going on :( Especially since I’ve been using Enchanted for months and it’s the best one so far. 

Thank you so much!

**Comment by icelaglace** [comment]
Hello, Ollama v0.1.28 seems to have fixed the issue, oddly. 

My apologies for the inconvenience on this issue, which happened at the time only on this software. 

It now works great without issues except the usual hang / app freeze that happens very rarely when a prompt answer is very long. 

I’ll close the issue, thank you so much again!

**Comment by icelaglace** [comment]
Hello, Ollama v0.1.28 seems to have fixed the issue, oddly.

My apologies for the inconvenience on this issue, which happened at the time only on this software.

It now works great without issues except the usual hang / app freeze that happens very rarely when a prompt answer is very long.

I’ll close the issue, thank you so much again!
