### ISSUE TITLE
llama2 always show even if not installed

### ISSUE THREAD

**Issue by eliseomartelli** [AugustDev/enchanted#39]
Hello, 
I'm writing this issue because the model llama2 is always shown in UI pickers even if it's not installed. 

<img width="182" alt="image" src="https://github.com/AugustDev/enchanted/assets/8228455/7ce7fc3a-fa73-4ef1-8f8b-b4f45da5f987">

<img width="477" alt="image" src="https://github.com/AugustDev/enchanted/assets/8228455/01bf76ca-5d87-42dc-9bc9-136d223fee27">

```
ollama ls
NAME            	ID          	SIZE  	MODIFIED       
codellama:latest	8fdf8f752f6e	3.8 GB	23 minutes ago	
mistral:latest  	61e88e884507	4.1 GB	43 minutes ago	
```

I'm running Version 1.5.5 (14)

**Comment by AugustDev** [comment]
Fixed, will be available in next release.
