### ISSUE TITLE
Feature Request : Add support for Authorization: Bearer

### ISSUE THREAD

**Issue by nikauroi** [AugustDev/enchanted#41]
I plan to use a proxy for ollama [like this](https://github.com/ParisNeo/ollama_proxy_server) to secure my endpoint. 

So, could you plan to allow to add support like this for the Bearer?
`curl -X <METHOD> -H "Authorization: Bearer <USER_KEY>" http://localhost:<PORT>/<PATH> [--data <POST_DATA>]`

BTW, the project looks very prommising.

**Comment by AugustDev** [comment]
No problem will support Bearer token. You'll be able to specify it in Settings

**Comment by nikauroi** [comment]
> No problem will support Bearer token. You'll be able to specify it in Settings

Nice! Looking forward.
