### ISSUE TITLE
Feature Request: Add code syntax highlighting

### ISSUE THREAD

**Issue by fabriciort** [AugustDev/enchanted#43]
The generation screen is already very beautiful! however, when I am generating programming or debugging information, I miss a highlight in the language used in the example code block.
Great Work!

* _I'm using the macOS version_

**Comment by eliseomartelli** [comment]
I think syntax highlighting can be achieved using the already used swift-markdown-ui library.
Example: https://github.com/gonzalezreal/swift-markdown-ui/blob/main/Examples/Demo/Demo/SyntaxHighlighter/SplashCodeSyntaxHighlighter.swift.

**Comment by AugustDev** [comment]
Great find, will be available on next update @eliseomartelli!
