### ISSUE TITLE
Android/windows support 

### ISSUE THREAD

**Issue by nivibilla** [AugustDev/enchanted#45]
Hi,

This is an amazing app. Is it possible to run it on Windows/android too? 
With a server backend that's running an openai compatible server

Thanks

**Comment by AugustDev** [comment]
Hi @nivibilla unfortunately Enchanted was built specifically for macOS/iOS and uses a lot of Apple SDKs. I'm not aware of any techniques allowing to convert the code to Android unfortunately.
