### ISSUE TITLE
enhancement: default model

### ISSUE THREAD

**Issue by qrkourier** [AugustDev/enchanted#5]
It would be helpful to have a way to designate one model as the default. That way, when starting a new conversation, it wouldn't be necessary to pick the model most of the time.

**Comment by AugustDev** [comment]
Great idea, I will implement!

**Comment by AugustDev** [comment]
<img width="386" alt="image" src="https://github.com/AugustDev/enchanted/assets/5672094/9b51ed08-078b-4ab5-8201-af2aed7836d3">

Hi @qrkourier thanks for feedback. I have implemented this feature. New version of the app should be approved by Apple by the end of day.
