### ISSUE TITLE
403 Forbidden & Thank you for your contribution!!!

### ISSUE THREAD

**Issue by limaolin2017** [AugustDev/enchanted#53]
<img width="559" alt="Screenshot 2024-03-16 at 22 26 41" src="https://github.com/AugustDev/enchanted/assets/28923721/77a5300e-f5a6-4d03-9ce2-544e52242fae">

**Comment by BileFlask** [comment]
I think this is an issue with the latest Ollama release. I was able to work around it by launching Ngrok like this:

ngrok http [port] --host-header="localhost:[port]"

**Comment by limaolin2017** [comment]
> I think this is an issue with the latest Ollama release. I was able to work around it by launching Ngrok like this:
> 
> ngrok http [port] --host-header="localhost:[port]"

yes, I use same command line, but Ollama reject access!

**Comment by dingshanliang** [comment]
<img width="602" alt="image" src="https://github.com/AugustDev/enchanted/assets/10998966/0d4a57d5-d176-4d3e-882b-70d8b79973cf">
Same issue. 
Is it possible that the token bearn is causing the problem? I don't know how to fill it out。
<img width="526" alt="image" src="https://github.com/AugustDev/enchanted/assets/10998966/ea91d34f-c077-4e53-80b2-94eaedd8bbeb">

**Comment by cocobeach** [comment]
> > I think this is an issue with the latest Ollama release. I was able to work around it by launching Ngrok like this:
> > ngrok http [port] --host-header="localhost:[port]"
> 
> This worked! Thank you

Worked for me too

**Comment by samqin123** [comment]
worked for me again, Marked in Apr/2024!!thanks

**Comment by chicheese** [comment]
IF you get a 403 forbidden error try this:

instead of running: ngrok http 11434
try this: ngrok http --host-header=rewrite localhost:11434

This should also work.

**Comment by AugustDev** [comment]
Thank you for investigating @BileFlask. Indeed it seems ollama now does host check for the API. I will update README to the proposed command.
