### ISSUE TITLE
Feature: Edit messages.

### ISSUE THREAD

**Issue by piv-pav** [AugustDev/enchanted#55]
Can we please have an option to edit user's messages, to simplify prompt engineering?

**Comment by AugustDev** [comment]
Hi, this is currently possible by right clicking the message.

**Comment by piv-pav** [comment]
Thanks, didn't know it's possible by the look at the interface, thanks for explaining, but I guess some pop-up icons would make an interface a bit more explicit and easier to use. Thanks, for the awesome project!

**Comment by AugustDev** [comment]
Implemented, releasing soon.
