### ISSUE TITLE
Feature: Regenerate response.

### ISSUE THREAD

**Issue by piv-pav** [AugustDev/enchanted#56]
Can we please have a feature to re-generate LLM response once again?

**Comment by AugustDev** [comment]
It is kind of possible now, by editing the chat message (right click) and clicking send again. But I agree it could be nice to have a simpler button

**Comment by AugustDev** [comment]
<img width="986" alt="image" src="https://github.com/AugustDev/enchanted/assets/5672094/7d0596f8-8707-4ac1-8e78-9737f112488d">

Adding Edit button for the upcoming release. ✅
