### ISSUE TITLE
Feature: Summary generated in chat window.

### ISSUE THREAD

**Issue by piv-pav** [AugustDev/enchanted#57]
First of all, thank you for you application, and for making it open-source!

Completions is truly an amazing feature, but it would be awesome if I could forward the processed output to the chat window (new chat for example) instead of typing it back to where it was selected. For summaries, or text/code analysis that would be much more convenient, plus I would have an access to history of those summaries (or other pre-defined text processing results)

**Comment by AugustDev** [comment]
Hi @piv-pav, thanks for the message. I was thinking of exactly the same thing. I will implemented ability to do this. Thank you for using Enchanted!

**Comment by AugustDev** [comment]
Implemented in next release ✅
