### ISSUE TITLE
Crash on clearing history

### ISSUE THREAD

**Issue by car5ten** [AugustDev/enchanted#59]
The App crashes if you are in a conversation and Press "delete all conversations" from settings menu

**Comment by AugustDev** [comment]
Hi @car5ten, could you try updating the app. I wonder if this issue still exists in latest version?

**Comment by car5ten** [comment]
Hey @AugustDev I just updated to the latest version and it still crashes

**Comment by car5ten** [comment]
fixed with latest version. thanks :)
