### ISSUE TITLE
Ollama Desktop can receive images but not read them.

### ISSUE THREAD

**Issue by joewinke** [AugustDev/enchanted#68]
I have downloaded ollama on ios and I don't see how to add images. For the mac desktop I can drop images in and it receives them, but when I query it says something along the lines of "I cannot see anything as I don't have the ability to process or view images. However, based on the context of your question, it seems that there is an image referred to as "img-0". Without seeing the image itself, it is impossible for me to describe its content."

![Screenshot 2024-04-12 at 8 32 04 AM](https://github.com/AugustDev/enchanted/assets/797297/6d090d28-06e1-4446-beab-548dd1b261bd)

**Comment by AugustDev** [comment]
Hi @joewinke what model are you using for images? Can you share version of ollama you use?

**Comment by joewinke** [comment]
OK that was a great question - I was using llama and mistral but realized upon your asking that perhaps I need a vision model. I downloaded llava and its working. Thank you for your help and creating this amazing app OSS.
