### ISSUE TITLE
bug: baseUrl trailing slash

### ISSUE THREAD

**Issue by qrkourier** [AugustDev/enchanted#7]
The app doesn't currently tolerate a trailing slash in the API base URL. If a trailing slash is present, then requests like `//api/tags` are sent, which are in turn not tolerated by Ollama.

It would be best if Enchanted strips the trailing `/` from the configured base URL because it re-adds it when composing requests.

**Comment by AugustDev** [comment]
Hi @qrkourier. Thanks for reporting. I just made a fix and will be releasing the app now. It should be on App Store later today or tomorrow morning.
