### ISSUE TITLE
How do completions work ?

### ISSUE THREAD

**Issue by bakman2** [AugustDev/enchanted#71]
I see the following:

<img width="367" alt="image" src="https://github.com/AugustDev/enchanted/assets/333960/d2e43de1-da46-4bbe-9f3b-625a6c84625a">

ok I do the shortcut K - if I type S with some text, model generates jibberish, how does this work ? can it be documented ?

**Comment by chriskempson** [comment]
In an application, highlight some text and then enter the keyboard shortcut to reveal the completions window.

**Comment by yoursbest** [comment]
> In an application, highlight some text and then enter the keyboard shortcut to reveal the completions window.

This works!
