### ISSUE TITLE
Enchanted macos application pings Ollama every 5 seconds

### ISSUE THREAD

**Issue by lewismacnow** [AugustDev/enchanted#73]
Can you add a feature to allow users to disable this behaviour?

![image](https://github.com/AugustDev/enchanted/assets/93997957/4e24b22d-3222-4909-856f-e2a7dc55f983)

**Comment by lewismacnow** [comment]
I guess this is from "startCheckingReachability()" ? 
Constantly pinging the server every 5 seconds is unnessesary.

Perhaps check one when the URI is updated then then once more on some event where it would be useful, like a chat window is opened?

**Comment by joewinke** [comment]
Yeah this used up all my bandwidth for ngrok. Needs to be disabled.

**Comment by pressdarling** [comment]
This ate up [ngrok's 20k free requests](https://ngrok.com/docs/guides/limits/#requests) in less than 16 hours for me simply by having left it open overnight on my second Mac. In fact, my logs are showing that my iPhone sent 1000 `HEAD`requests - 1000 being the limit that ngrok's traffic inspector will display - for 27 `GET` requests and 50 `POST` requests. 

This issue leaves users with no suitable workaround given that Cloudflare Tunnels appear to have mixed results (I hadn't investigated this yet but can there are some other issues there e.g. #88 #48), which make this an even more pressing concern and limits usage to the local network e.g. `http://192.168.x.x:11434`. I also have AnythingLLM running on my Macbooks without anything like this happening, no other tools I've tried do this either.

I like the look of the solution in #102 at a glance. Some duplicate issues to consolidate/close/merge: #78, #98.

**Comment by AugustDev** [comment]
Fixed by https://github.com/AugustDev/enchanted/pull/102. Releasing new version now!

**Comment by joewinke** [comment]
I downloaded the new version and when the ios app is open it is still pinging every 5 seconds, however when the app is closed or not visible it stops pinging, which seems like the intended outcome. Thank you! I'm closing out https://github.com/AugustDev/enchanted/issues/78

**Comment by unclebryan719** [comment]
> This ate up [ngrok's 20k free requests](https://ngrok.com/docs/guides/limits/#requests) in less than 16 hours for me simply by having left it open overnight on my second Mac. In fact, my logs are showing that my iPhone sent 1000 `HEAD`requests - 1000 being the limit that ngrok's traffic inspector will display - for 27 `GET` requests and 50 `POST` requests.
> 
> This issue leaves users with no suitable workaround given that Cloudflare Tunnels appear to have mixed results (I hadn't investigated this yet but can there are some other issues there e.g. #88 #48), which make this an even more pressing concern and limits usage to the local network e.g. `http://192.168.x.x:11434`. I also have AnythingLLM running on my Macbooks without anything like this happening, no other tools I've tried do this either.
> 
> I like the look of the solution in #102 at a glance. Some duplicate issues to consolidate/close/merge: #78, #98.

can Enchanted connect AnythingLLM？

**Comment by joewinke** [comment]
@unclebryan719 what do you mean? do you mean ollama?

**Comment by lewismacnow** [comment]
> > This ate up [ngrok's 20k free requests](https://ngrok.com/docs/guides/limits/#requests) in less than 16 hours for me simply by having left it open overnight on my second Mac. In fact, my logs are showing that my iPhone sent 1000 `HEAD`requests - 1000 being the limit that ngrok's traffic inspector will display - for 27 `GET` requests and 50 `POST` requests.
> > This issue leaves users with no suitable workaround given that Cloudflare Tunnels appear to have mixed results (I hadn't investigated this yet but can there are some other issues there e.g. #88 #48), which make this an even more pressing concern and limits usage to the local network e.g. `http://192.168.x.x:11434`. I also have AnythingLLM running on my Macbooks without anything like this happening, no other tools I've tried do this either.
> > I like the look of the solution in #102 at a glance. Some duplicate issues to consolidate/close/merge: #78, #98.
> 
> can Enchanted connect AnythingLLM？

Not yet but that would be very cool. The API is not fully compatible yet. Create an issue for a feature request and me or someone else will try to make it available
