### ISSUE TITLE
ngrok's warning page blocks access to the API

### ISSUE THREAD

**Issue by algieg** [AugustDev/enchanted#9]
When I follow the instructions and use ngrok, it runs properly (as displayed on your instructions video) and the app sees the ollama server and available models, however, once I use the app's chat, ngrok displays "POST /api/chat                 404 Not Found". I assume it's because of the ngrok warning page that's displayed on other devices on first visit. Can you add an option in the app to handle it? I assume following this "_Set and send an ngrok-skip-browser-warning request header with any value._" would work.

![image](https://github.com/AugustDev/enchanted/assets/113560170/7e76745b-051d-4e20-942f-67dc0b0f63d7)

Thank you!

**Comment by AugustDev** [comment]
Hi @algieg, what is the version of Ollama that you're using? Could you do `ollama -v` and share the result?

I have used Ollama chat API which came out with `v0.1.14`, perhaps there's a possibility you are using older version?

**Comment by algieg** [comment]
You're completely right, I updated Ollama on another machine and confused it with this one. I confirm it works on 0.1.14. Apologies for the trouble!

**Comment by AugustDev** [comment]
No worries at all! Glad it works.
